=== specter01wj/ShangXueTang_Course/T1809-Java_Architect/01_Java_Beginner/ExtraWork/学到猝死—尚学堂百战在线购物系统/源码/BZMallServer/xml/goods.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT goods (good*)>
<!ELEMENT good (goodName,goodPrice,goodType,goodDesception,goodRepertory,merchantID,goodBrand,goodSellCount,url)>
<!ATTLIST good ID CDATA #REQUIRED>
<!ELEMENT goodName (#PCDATA)>
<!ELEMENT goodPrice (#PCDATA)>
<!ELEMENT goodType (#PCDATA)>
<!ELEMENT goodDesception (#PCDATA)>
<!ELEMENT goodRepertory (#PCDATA)>
<!ELEMENT goodBrand (#PCDATA)>
<!ELEMENT goodSellCount (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== specter01wj/ShangXueTang_Course/T1809-Java_Architect/01_Java_Beginner/ExtraWork/学到猝死—尚学堂百战在线购物系统/源码/BZMallServer/xml/goods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE goods SYSTEM "goods.dtd">

<goods>
  <good ID="20142203744">
    <goodName>伊利</goodName>
    <goodPrice>5.0</goodPrice>
    <goodType>营养品</goodType>
    <goodDesception>伊利纯牛奶</goodDesception>
    <goodRepertory>500</goodRepertory>
    <merchantID>user1504057858984</merchantID>
    <goodBrand>伊利</goodBrand>
    <goodSellCount>902</goodSellCount>
    <url>src/com/xdcs/swing/image/milk.jpg</url>
  </good>
  <good ID="201">
    <goodName>百事</goodName>
    <goodPrice>3.5</goodPrice>
    <goodType>饮料</goodType>
    <goodDesception>额呵呵呵呵呵</goodDesception>
    <goodRepertory>300</goodRepertory>
    <merchantID>user1504057858984</merchantID>
    <goodBrand>百事</goodBrand>
    <goodSellCount>293</goodSellCount>
    <url>src/com/xdcs/swing/image/7up.jpg</url>
  </good>
  <good ID="202">
    <goodName>可口</goodName>
    <goodPrice>3.5</goodPrice>
    <goodType>饮料</goodType>
    <goodDesception>嗬嗬嗬嗬</goodDesception>
    <goodRepertory>300</goodRepertory>
    <merchantID>user1504057858984</merchantID>
    <goodBrand>可口</goodBrand>
    <goodSellCount>90</goodSellCount>
    <url>src/com/xdcs/swing/image/kekou.jpg</url>
  </good>
  <good ID="201730022">
    <goodName>百事</goodName>
    <goodPrice>3.0</goodPrice>
    <goodType>薯片</goodType>
    <goodDesception>周杰伦代言的</goodDesception>
    <goodRepertory>4566</goodRepertory>
    <merchantID>user1504057858984</merchantID>
    <goodBrand>百事</goodBrand>
    <goodSellCount>20</goodSellCount>
    <url>src/com/xdcs/swing/image/kebike.jpg</url>
  </good>
  <good ID="20178899">
    <goodName>康帅傅</goodName>
    <goodPrice>2.5</goodPrice>
    <goodType>方便面</goodType>
    <goodDesception>康师傅方便面，有嚼劲</goodDesception>
    <goodRepertory>300</goodRepertory>
    <merchantID>lisi</merchantID>
    <goodBrand>康帅傅</goodBrand>
    <goodSellCount>10</goodSellCount>
    <url>src/com/xdcs/swing/image/kashifu.jpg</url>
  </good>
  <good ID="201788999">
    <goodName>康帅傅</goodName>
    <goodPrice>19.2</goodPrice>
    <goodType>方便面</goodType>
    <goodDesception>鸡肉味，嘎嘣脆</goodDesception>
    <goodRepertory>2000</goodRepertory>
    <merchantID>user1504057858984</merchantID>
    <goodBrand>康帅傅</goodBrand>
    <goodSellCount>0</goodSellCount>
    <url>src/com/xdcs/swing/image/kangshifu.jpg</url>
  </good>
</goods>
