=== specter01wj/ShangXueTang_Course/T1809-Java_Architect/01_Java_Beginner/ExtraWork/学到猝死—尚学堂百战在线购物系统/源码/BZMallServer/xml/order.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT orders (order*)>
<!ATTLIST order ID CDATA #REQUIRED>
<!ELEMENT order (goodsMsg,orderTime,consumerID,merchantID,recvOrder,checkPay,payTime,deliver)>
<!ELEMENT goodsMsg (good*)>
<!ATTLIST good goodID CDATA #REQUIRED>
<!ELEMENT good (count)>
<!ELEMENT count (#PCDATA)>
<!ELEMENT orderTime (#PCDATA)>
<!ELEMENT consumerID (#PCDATA)>
<!ELEMENT merchantID (#PCDATA)>
<!ELEMENT recvOrder (#PCDATA)>
<!ELEMENT checkPay (#PCDATA)>
<!ELEMENT payTime (#PCDATA)>
<!ELEMENT deliver (#PCDATA)>

=== specter01wj/ShangXueTang_Course/T1809-Java_Architect/01_Java_Beginner/ExtraWork/学到猝死—尚学堂百战在线购物系统/源码/BZMallServer/xml/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders SYSTEM "order.dtd">

<orders>
  <order ID="xdcs1504184548955">
    <goodsMsg>
      <good goodID="20142203744">
        <count>12</count>
      </good>
      <good goodID="201">
        <count>33</count>
      </good>
    </goodsMsg>
    <orderTime>2017-08-31 09:02:28</orderTime>
    <consumerID>user1504058025827</consumerID>
    <merchantID>user1504057858984</merchantID>
    <recvOrder>true</recvOrder>
    <checkPay>true</checkPay>
    <payTime>未支付</payTime>
    <deliver>true</deliver>
  </order>
  <order ID="xdcs1504185540685">
    <goodsMsg>
      <good goodID="20178899">
        <count>10</count>
      </good>
      <good goodID="201730022">
        <count>20</count>
      </good>
    </goodsMsg>
    <orderTime>2017-08-31 09:19:00</orderTime>
    <consumerID>user1504058025827</consumerID>
    <merchantID>lisi</merchantID>
    <recvOrder>false</recvOrder>
    <checkPay>true</checkPay>
    <payTime>未支付</payTime>
    <deliver>false</deliver>
  </order>
</orders>
